import type { Metadata } from "next";
import { Open_Sans, Sacramento } from "next/font/google"
import "./globals.css";

const sacramento = Sacramento({
  weight: '400',
  subsets: ['latin'],
  display: "swap",
  variable: '--font-sacramento'
})

const open_sans = Open_Sans({
  subsets: ['latin'],
  display: "swap",
  variable: '--font-open-sans'
})

export const metadata: Metadata = {
  title: "VENDEDOR DE ALTA PERFORMACE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${sacramento.variable} ${open_sans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
